In [6]:
import pandas as pd


arquivo =  r"..\data\daos_geograficos\RELATORIO_DTB_BRASIL_2024_MUNICIPIOS.xls"

# Leitura do arquivo
df = pd.read_excel(arquivo, engine="xlrd", skiprows=6)

display(df)

,UF,Nome_UF,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,Município,Código Município Completo,Nome_Município,Unnamed: 9
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,NaN
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,379,1100379,Alto Alegre dos Parecis,NaN
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,403,1100403,Alto Paraíso,NaN
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,346,1100346,Alvorada D'Oeste,NaN
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,23,1100023,Ariquemes,NaN
...,...,...,...,...,...,...,...,...,...,...
5566,52,Goiás,5201,Goiânia,520002,Anápolis,22005,5222005,Vianópolis,NaN
5567,52,Goiás,5202,Itumbiara,520009,Piracanjuba,22054,5222054,Vicentinópolis,NaN
5568,52,Goiás,5206,Luziânia - Águas Lindas de Goiás,520022,Flores de Goiás,22203,5222203,Vila Boa,NaN
5569,52,Goiás,5205,Porangatu - Uruaçu,520018,Ceres - Rialma - Goianésia,22302,5222302,Vila Propício,NaN
5570,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,NaN

In [7]:

df.columns = [col.strip() for col in df.columns]

# Filtrar apenas RS (UF = 43)
df = df[df['Nome_UF'] == 'Rio Grande do Sul']

# Seleção das colunas relevantes para o estudo
colunas_utilizadas = {
    'UF': 'uf',
    'Nome_UF': 'nome_uf',
    'Região Geográfica Intermediária': 'regiao_intermediaria',
    'Nome Região Geográfica Intermediária': 'nome_regiao_intermediaria',
    'Região Geográfica Imediata': 'regiao_imediata',
    'Nome Região Geográfica Imediata': 'nome_regiao_imediata',
    'Município': 'codigo_municipio',
    'Nome_Município': 'nome_municipio'
}

df = df[list(colunas_utilizadas.keys())]
df = df.rename(columns=colunas_utilizadas)

# Limpeza de dados
df['nome_municipio'] = df['nome_municipio'].str.strip().str.upper()

df['codigo_municipio'] = df['codigo_municipio'].astype(str)

df['uf_sigla'] = 'RS'

# Salvar dataset tratado

df.to_csv(r"..\data\daos_geograficos\dados_tratados\dados_geograficos_RS.csv", index=False)

print("✅ Dados geográficos tratados com sucesso!")

✅ Dados geográficos tratados com sucesso!

In [8]:
df

,uf,nome_uf,regiao_intermediaria,nome_regiao_intermediaria,regiao_imediata,nome_regiao_imediata,codigo_municipio,nome_municipio,uf_sigla
4606,43,Rio Grande do Sul,4302,Pelotas,430010,Bagé,34,ACEGUÁ,RS
4607,43,Rio Grande do Sul,4306,Passo Fundo,430032,Tapejara - Sananduva,59,ÁGUA SANTA,RS
4608,43,Rio Grande do Sul,4303,Santa Maria,430011,Santa Maria,109,AGUDO,RS
4609,43,Rio Grande do Sul,4305,Ijuí,430018,Ijuí,208,AJURICABA,RS
4610,43,Rio Grande do Sul,4305,Ijuí,430019,Santa Rosa,307,ALECRIM,RS
...,...,...,...,...,...,...,...,...,...
5098,43,Rio Grande do Sul,4307,Caxias do Sul,430038,Nova Prata - Guaporé,23606,VISTA ALEGRE DO PRATA,RS
5099,43,Rio Grande do Sul,4305,Ijuí,430021,Três Passos,23705,VISTA GAÚCHA,RS
5100,43,Rio Grande do Sul,4305,Ijuí,430020,Santo Ângelo,23754,VITÓRIA DAS MISSÕES,RS
5101,43,Rio Grande do Sul,4308,Santa Cruz do Sul - Lajeado,430041,Lajeado,23770,WESTFÁLIA,RS
5102,43,Rio Grande do Sul,4301,Porto Alegre,430003,Tramandaí - Osório,23804,XANGRI-LÁ,RS